dist: trusty
sudo: required
group: beta
language: node_js
node_js:
  - "9"

cache:
  directories:
    - node_modules

before_script:
  - truffle version

jobs:
  # XXX fast_finish doesn't work with stages yet. See
  # https://github.com/travis-ci/travis-ci/issues/8425
  # --elopio - 20180531
  fast_finish: true
  allow_failures:
    - env: SOLIDITY_COVERAGE=true
    - env: SOLC_NIGHTLY=true
  include:
    # Run the unit test suite three times in parallel.
    - stage: tests
      name: "linting"
      script: npm run lint:sol
    - stage: tests
      name: "unit tests"
      script: 
        - npm run ganache-cli &
        - truffle test
